In [2]:
import numpy as np
A = np.array( [[10.,2.,1.],
              [6. ,5.,4.],
              [1.,4.,7.]])
print(A)              

[[10.  2.  1.]
 [ 6.  5.  4.]
 [ 1.  4.  7.]]


In [3]:
print(np.ndim(A))

2


In [4]:
print(np.shape(A))

(3, 3)


In [5]:
print(A.T)

[[10.  6.  1.]
 [ 2.  5.  4.]
 [ 1.  4.  7.]]


In [6]:
import scipy.linalg as sl
print(sl.inv(A))

[[ 0.14285714 -0.07518797  0.02255639]
 [-0.28571429  0.51879699 -0.2556391 ]
 [ 0.14285714 -0.28571429  0.28571429]]


In [7]:
print(sl.det(A))

133.00000000000003


In [8]:
print(A @ sl.inv(A))
print()

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.22044605e-16]
 [-8.32667268e-17 -1.11022302e-16  1.00000000e+00]]


In [9]:
print(np.dot(A,sl.inv(A)))
print('\n')
print(A.dot(sl.inv(A)))


[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.22044605e-16]
 [-8.32667268e-17 -1.11022302e-16  1.00000000e+00]]


[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.22044605e-16]
 [-8.32667268e-17 -1.11022302e-16  1.00000000e+00]]


In [11]:
print(np.zeros(3))
print('\n')
print(np.zeros((3,3)))

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
A = np.array( [[10.,2.,1.],
              [6. ,5.,4.],
              [1.,4.,7.]])
print(type(A))
type(np.mat(A))

<class 'numpy.ndarray'>


numpy.matrix

In [17]:
print(np.mat(A) * np.mat(sl.inv(A)))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.22044605e-16]
 [-8.32667268e-17 -1.11022302e-16  1.00000000e+00]]


In [20]:
print(A[0,1])
print(A[0,:])
print(A[-1,:])
print(A[:,1])
print(A[1:3,1:3])


2.0
[10.  2.  1.]
[1. 4. 7.]
[2. 5. 4.]
[[5. 4.]
 [4. 7.]]


In [24]:
A = np.array([[2., 3.],
              [1., -4.]])
print('det A = ', sl.det(A))
b = np.array([7.,3.])
print('A^-1 @ b = ', sl.inv(A)@ b)

det A =  -11.0
A^-1 @ b =  [3.36363636 0.09090909]


In [25]:
print('A^-1 @ b =',sl.solve(A,b))

A^-1 @ b = [3.36363636 0.09090909]


In [26]:
print(np.allclose(np.array([37./11., 1./11.]), sl.solve(A,b)))

True


In [30]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([2,4,6])
print('A =',A)
print('b =',b)
print('size of A:',A.size,'and shape of A:',A.shape)
print('size of b:',b.size,'and shape of b:',b.shape)
I = np.eye(3)
print('I = ',I)
A = A + I
print('A=',A)
A[:,2] = b
print("A =", A)
x = sl.solve(A,b)
print('x = ',x)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [2 4 6]
size of A: 9 and shape of A: (3, 3)
size of b: 3 and shape of b: (3,)
I =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A= [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
A = [[2. 2. 2.]
 [4. 6. 4.]
 [7. 8. 6.]]
x =  [0. 0. 1.]
