In [1]:
import numpy as np
def upper_triangle(A,b):
    n = np.size(b)
    rows, cols = np.shape(A)
    assert rows ==cols
    assert rows == n
    for k in range(n-1):#从第二列开始遍历主元下方所有列，k是正在处理的列号
        for i in range(k+1,n):#遍历主元下面的所有行，i是行号
            s = (A[i,k] / A[k,k])# 第i行元素除以其主元元素，消元需要的系数
            for j in range(k,n):#遍历第i行下方元素
                A[i,j] = A[i,j] -s*A[k,j]#消除后A[i,j]等于0
            b[i] = b[i] -s*b[k]#更新方程右侧
    return A,b

In [ ]:
A = np.array([[2., 3., -4.],
              [6., 8., 2.],
              [4., 8., -6.]])
b = np.array([5., 3., 19.])
n = np.size(b)
rows, cols = np.shape(A)
assert rows ==cols
assert rows == n
for k in range(n-1):#n=3 k=0,1
    print('k',k)
    for i in range(k+1,n):#i=1,2;i=2 
        print('i',i)
        for j in range(k,n):#j=0,1,2;j=0,1,2;j=1,2
            print('j',j)

In [2]:
A = np.array([[2., 3.,],
              [1., -4.]])
b = np.array([7., 3.])
A,b = upper_triangle(A,b)
print('our A matrix following row operations to transform it into upper-triangular form:')
print(A)
print('the correspondingly updated b vector:')
print(b)

our A matrix following row operations to transform it into upper-triangular form:
[[ 2.   3. ]
 [ 0.  -5.5]]
the correspondingly updated b vector:
[ 7.  -0.5]


In [3]:
A = np.array([[2., 3., -4.],
              [6., 8., 2.],
              [4., 8., -6.]])
b = np.array([5., 3., 19.])

A, b = upper_triangle(A, b)

print('\nOur A matrix following row operations to transform it into upper-triangular form:')
print(A)
print('The correspondingly updated b vector:')
print(b)


Our A matrix following row operations to transform it into upper-triangular form:
[[ 2.  3. -4.]
 [ 0. -1. 14.]
 [ 0.  0. 30.]]
The correspondingly updated b vector:
[  5. -12. -15.]


In [4]:
A = np.array([[2., 3., -4.],
              [6., 8., 2.],
              [4., 8., -6.]])
b = np.array([5., 3., 19.])

A, b = upper_triangle(A, b)

print('\nOur A matrix following row operations to transform it into upper-triangular form:')
print(A)
print('The correspondingly updated b vector:')
print(b)


Our A matrix following row operations to transform it into upper-triangular form:
[[ 2.  3. -4.]
 [ 0. -1. 14.]
 [ 0.  0. 30.]]
The correspondingly updated b vector:
[  5. -12. -15.]


In [8]:
def back_substitution(A,b):
    n = np.size(b)
    rows, cols = np.shape(A)
    assert(rows ==cols)
    assert rows ==n
    assert np.allclose(A, np.triu(A))
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        s = 0.0
        for j in range(k+1, n):
            s = s + A[k,j] * x[j]
        x[k] = (b[k] - s) / A[k,k]
    return x

In [9]:
A = np.array([[2., 3., -4.],
              [6., 8., 2.],
              [4., 8., -6.]])
b = np.array([5., 3., 19.])

A_upp, b_upp = upper_triangle(A, b)

# Print the solution using our codes
x = back_substitution(A_upp, b_upp)
print('Our solution: ',x)  

# Check our answer against what SciPy gives us by multiplying b by A inverse 
import scipy.linalg as sl

print('SciPy solution: ',sl.inv(A) @ b)
print('Success: ', np.allclose(x, sl.inv(A) @ b))

Our solution:  [-6.   5.  -0.5]
SciPy solution:  [-6.   5.  -0.5]
Success:  True


In [10]:
def upper_triangle2(A,B):
    n ,m = np.shape(A)
    assert(n == m)
    for k in range(n-1):
        for i in range(k+1,n):
            s = (A[i,k] / A[k,k])
            for j in range(n):
                A[i,j] = A[i,j] - s*A[k,j]
                B[i,j] = B[i,j] - s*B[k,j]
def lower_triangle2(A,B):
    n,m = np.shape(A)
    assert n==m
    for k in range(n-1, -1, -1):
        for i in range(k-1,-1,-1):
            s=(A[i,k] / A[k,k])
            for j in range(n):
                A[i,j] = A[i,j] - s*A[k,j]
                B[i,j] = B[i,j] - s*B[k,j]

In [11]:
# Let's redefine A as our matrix above
A = np.array([[2., 3., -4.],
              [3., -1., 2.],
              [4., 2., 2.]])

# and B is the identity of the corresponding size
B = np.eye(np.shape(A)[0])

# transform A into upper triangular form 
# (and perform the same operations on B)
upper_triangle2(A, B)
print('Upper triangular transformed A = ')
print(A)

# now make this updated A lower triangular as well 
# (the result should be diagonal)
lower_triangle2(A, B)
print('\nand following application of our lower triangular function = ')
print(A)

# The final step to achieve the identity is just to divide each row through by the value 
# of the diagonal to end up with 1's on the main diagonal and 0 everywhere else.
for i in range(np.shape(A)[0]):
    B[i, :] = B[i, :]/A[i, i]
    A[i, :] = A[i, :]/A[i, i]

# the final A should be the identity
print('\nOur final transformed A = ')
print(A)

# the final B should therefore be the inverse of the original B
print('\nand the correspondingly transformed B = ')
print(B)

# let's compute the inverse using built-in functions and check
# we get the same answer (we need to reinitialise A)
A = np.array([[2., 3., -4.], [3., -1., 2.], [4., 2., 2.]])
print('\nSciPy computes the inverse as:')
print(sl.inv(A))

# B should now store the inverse of the original A - let's check
print('\nSuccess: ', np.allclose(B, sl.inv(A)))

Upper triangular transformed A = 
[[ 2.          3.         -4.        ]
 [ 0.         -5.5         8.        ]
 [ 0.          0.          4.18181818]]

and following application of our lower triangular function = 
[[ 2.          0.          0.        ]
 [ 0.         -5.5         0.        ]
 [ 0.          0.          4.18181818]]

Our final transformed A = 
[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]

and the correspondingly transformed B = 
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

SciPy computes the inverse as:
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

Success:  True


In [12]:
def swap_row(A,b,i,j):
    if i == j:
        return
    print('swapping rows', i, 'and',j)
    iA = np.copy(A[i,:])
    ib = np.copy(b[i])
    A[i,:] = A[j,:]
    b[i] = b[j]
    A[j,:] = iA
    b[j] = ib

def upper_triangle_pp(A,b):
    n = np.size(b)
    rows, cols =np.shape(A)
    assert rows == cols
    assert rows ==n
    for k in range(n-1):
        kmax = k
        for i in range(k+1,n):
            if abs(A[kmax,k]) < abs(A[i,k]):
                kmax = i
        swap_row(A,b,kmax,k)
        for i in range(k+1,n):
            s = (A[i,k] / A[k,k])
            for j in range(k,n):
                A[i,j] = A[i,j] - s*A[k,j]
            b[i] = b[i] - s*b[k]

A = np.array([[2., 3.,-4.],
              [3.,-1., 2.],
              [4., 2., 2.,]])
b = np.array([10.,3.,8.])
upper_triangle_pp(A,b)
print('\nA and b with row swaps:')
print(A)
print(B)
x1 = back_substitution(A,b)
A = np.array([
              [2.,3.,-4.],
              [3.,-1.,2.],
              [4.,2.,2.] 
])
b = np.array([10.,3.,8.,])
upper_triangle(A,b) 
print(A)
print(B)
x2 = back_substitution(A,b)
print('\n These two upper triangular systems are equivalent(i.e. have the same solution):', np.allclose(x1,x2))


swapping rows 2 and 0

A and b with row swaps:
[[ 4.   2.   2. ]
 [ 0.  -2.5  0.5]
 [ 0.   0.  -4.6]]
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]
[[ 2.          3.         -4.        ]
 [ 0.         -5.5         8.        ]
 [ 0.          0.          4.18181818]]
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

 These two upper triangular systems are equivalent(i.e. have the same solution): True
